# Generated by Django 3.1.4 on 2020-12-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0007_auto_20201210_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(blank=True, choices=[('p', 'Prestado'), ('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Disponibilidad del libro', max_length=1),
        ),
    ]
