# Generated by Django 3.1.4 on 2020-12-14 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0014_auto_20201214_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='id',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mi_aplicacion.ejemplar'),
        ),
    ]
