# Generated by Django 3.1.4 on 2020-12-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_auto_20201210_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.FileField(blank=True, upload_to='mi_aplicacion/static/img'),
        ),
    ]
