# Generated by Django 3.1.4 on 2020-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_auto_20201210_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['devolucion']},
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Disponibilidad del libro', max_length=1),
        ),
    ]
