# Generated by Django 3.1.4 on 2020-12-10 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0009_ejemplar_prestatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='devolucion',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 9)),
        ),
    ]
