# Generated by Django 3.1.4 on 2020-12-10 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0010_auto_20201210_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='devolucion',
            field=models.DateField(blank=True, default=datetime.date(2020, 12, 17)),
        ),
    ]
