# Generated by Django 3.1.4 on 2020-12-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0012_auto_20201211_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
