# Generated by Django 3.1.4 on 2020-12-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0015_auto_20201214_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.FileField(blank=True, upload_to='static/img'),
        ),
    ]
